export const profileFormFields = [
    {
        label: 'Аватар',
        inputName: 'avatar',
        inputId: 'avatar',
        // value: 'https://avatars.githubusercontent.com/u/103450915?v=4',
        placeholder: 'Ссылка',
    },
    {
        type: 'email',
        label: 'Почта',
        inputId: 'email',
        inputName: 'email',
        placeholder: 'example@ex.com',
    },
    {
        label: 'Логин',
        inputId: 'login',
        inputName: 'login',
        placeholder: 'example_2004',
    },
    {
        label: 'Имя',
        inputId: 'first_name',
        inputName: 'first_name',
        placeholder: 'Иван',
    },
    {
        label: 'Фамилия',
        inputId: 'second_name',
        inputName: 'second_name',
        placeholder: 'Иванов',
    },
    {
        label: 'Отображаемое имя',
        inputId: 'display_name',
        inputName: 'display_name',
        type: 'name',
        placeholder: 'Ванчоус',
    },
    {
        label: 'Телефон',
        inputId: 'phone',
        inputName: 'phone',
        placeholder: '+7 (952) 752 52 52',
    },
    {
        label: 'Старый пароль',
        inputId: 'newPassword',
        inputName: 'newPassword',
        type: 'password',
        placeholder: '**********',
    },
    {
        label: 'Старый пароль',
        inputId: 'oldPassword',
        inputName: 'oldPassword',
        type: 'password',
        placeholder: '**********',
    },
];
